### ISSUE TITLE
Begin work on data conversion of RADAR time series data

### ISSUE THREAD

**Issue by brian428** [USACE/water-ui-old#122]
I have already created a time series bundle, so I think we need a new selector that can return the time series data in a format that we can feed into Plotly. 

A Plotly time series chart config looks like this: [https://plotly.com/javascript/time-series/](https://plotly.com/javascript/time-series/). As you can see, it needs an x array and a y array. 

However, the RADAR data (see examples in mockdata/radar-time-series.json) is in a format like this:

```
{
        "office": "NAB",
        "name": "Indian Rock.Elev.Inst.15Minutes.0.DCP-rev",
        "alternate-names": ["01574700.Elev.Inst.15Minutes.0.DCP-rev", "CE59BD90.Elev.Inst.15Minutes.0.DCP-rev", "PA00007.Elev.Inst.15Minutes.0.DCP-rev", "YRKP1.Elev.Inst.15Minutes.0.DCP-rev", "ctp.Elev.Inst.15Minutes.0.DCP-rev"],
        "regular-interval-values": {
          "interval": "PT15M",
          "unit": "ft PCD",
          "segment-count": 1,
          "segments": [{
              "first-time": "2020-10-26T17:45:00Z",
              "last-time": "2020-10-27T17:00:00Z",
              "value-count": 94,
              "comment": "value, quality code",
              "values": [[373.05, 3], [373.05, 3], [373.05, 3], [373.05, 3], [373.05, 3], [373.05, 3], [373.05, 3], [373.05, 3], [373.05, 3], [373.06, 3], [373.06, 3], [373.06, 3], [373.06, 3], [373.07, 3], [373.07, 3], [373.07, 3], [373.07, 3], [373.07, 3], [373.07, 3], [373.07, 3], [373.07, 3], [373.07, 3], [373.07, 3], [373.07, 3], [373.07, 3], [373.07, 3], [373.07, 3], [373.06, 3], [373.06, 3], [373.05, 3], [373.04, 3], [373.04, 3], [373.03, 3], [373.01, 3], [373, 3], [372.97, 3], [372.96, 3], [372.93, 3], [372.9, 3], [372.87, 3], [372.84, 3], [372.81, 3], [372.76, 3], [372.72, 3], [372.68, 3], [372.63, 3], [372.59, 3], [372.55, 3], [372.51, 3], [372.48, 3], [372.46, 3], [372.45, 3], [372.44, 3], [372.44, 3], [372.46, 3], [372.48, 3], [372.52, 3], [372.56, 3], [372.6, 3], [372.64, 3], [372.69, 3], [372.74, 3], [372.78, 3], [372.82, 3], [372.86, 3], [372.89, 3], [372.92, 3], [372.94, 3], [372.94, 3], [372.95, 3], [372.96, 3], [372.97, 3], [372.98, 3], [372.99, 3], [372.99, 3], [372.99, 3], [373, 3], [373, 3], [373, 3], [373, 3], [373, 3], [373, 3], [373, 3], [373, 3], [373, 3], [373, 3], [373, 3], [373, 3], [373, 3], [373, 3], [373, 3], [373, 3], [372.99, 3], [372.99, 3]]
            }
          ]
        }
``` 

The `values` array will be the Y axis values. But the X values (time) will have to be synthesized.

So our selector will need to take the start date, then loop over each value item and add a date object to the X array. In this case, each date is 15 minutes apart (as set by the `interval`). 

As a fun aside, as you can see from the mock JSON, there are different intervals for different series, so we'll also need a function to parse that interval so the "dates X array builder" logic knows how much to increment the Dates it is building.

Hopefully this makes sense? If so, take a crack at it.

**Comment by mohitb3** [comment]
In the mock data, the `time-series` array has five objects. Will we want to graph all five objects? Also will `segments` always be an array of one object?

**Comment by brian428** [comment]
Yes we will want to be able to graph all the various time series. Probably with one "current" plot as a larger more detailed plot, and the others as a list with simple sparkline plots. I'll attach a screenshot of the goal we are shooting for.

Regarding segments, I'm not sure if it will always be an array with 1 element, but my guess is that it could be more than one. For now, just focus on dealing with the first element and we'll see what we need to do to handle more than one.
![time series wireframe](https://user-images.githubusercontent.com/140338/97994188-0844a500-1db3-11eb-87a9-4ecc9f1eac26.png)
