### ISSUE TITLE
DistrictAndBasin component (hardcoded options)

### ISSUE THREAD

**Issue by brian428** [USACE/water-ui-old#13]
Create a simple component with District and Basin select fields side by side. To start with, just hard code some options. Then we can work out a JSON structure that allows the selected District to filter which Basins are shown.

**Comment by brian428** [comment]
Hey Dan just curious, did this get merged into develop, or is it part of one of your other branches?

**Comment by dlin2102** [comment]
It's in my branch. feature/6. I'll make a pull request for it.
