### ISSUE TITLE
Add map filters for Dam and Lake

### ISSUE THREAD

**Issue by brian428** [USACE/water-ui-old#179]
We should be able to add Dam and Lake filters to the location type dropdown. For these, we have to inspect the location summary objects and only include ones where `lake_indicator` and/or `dam_indicator` are set to "T".

**Comment by mohitb3** [comment]
@brian428 a lot of dams have both the `lake_indicator` and `dam_indicator` set to "T". For example Somerville Lake in Texas has two location ids associated with it: id 187048 is a dam and id 381049 is a lake, but both ids have the same lat/lon coordinates. The dam id, 187048, has `lake_indicator` and `dam_indicator` set to "T", but the lake id, 381049, has `lake_indicator` = "T" and `dam_indicator` = "F". I'm guessing that when the user selects the Lake filter, we should only display locations with `lake_indicator` = "T" and `dam_indicator` = "F"?

**Comment by brian428** [comment]
hmm for now that sounds fine. I'll try to ask Brett and Jeremy to see if they can shed any light.
