### ISSUE TITLE
LocationDamProfile

### ISSUE THREAD

**Issue by brian428** [USACE/water-ui-old#42]
Show dam profile info in the detail view, using mock JSON. For now, just make a simple table for the data. If the decision is made to make this into a fancier graphic (like the current site), we can do that later when we know more.

**Comment by brian428** [comment]
Dan, I have also added some mock "dam history" data to the [location-detail.json](https://github.com/USACE/water-ui/blob/develop/public/mockdata/location-detail.json). So for this tabular display of the dam info, I would use the history item with the most recent date (right now there is only one history item in the array anyway). The table can just list out the data, such as the date, in flow, out flow, the water levels, etc.

**Comment by dlin2102** [comment]
Sounds good.  So I would have multiple tables in Location Info. One with metadata and the other history.

[cid:image001.png@01D69D5B.1EB7E000]
