### ISSUE TITLE
LocationInformation

### ISSUE THREAD

**Issue by brian428** [USACE/water-ui-old#43]
The location information section of the detail view, using mock JSON.

**Comment by brian428** [comment]
Dan, for starters, I would just output some basic info from the location detail such as time zone, county, state, etc. Once PR #90 is merged, you can pass in the location detail to the LocationInformation via props (like I am doing for the detail header component) and use some of the additional new properties like water elevation.

**Comment by dlin2102** [comment]
Yeah, sounds good. I'm just creating a dumb table component for now.
